"""Default data for the kekaoxing reliability test scheduler.

Contains DEFAULT_TASKS (25 reliability test tasks) and DEFAULT_RESOURCES
(15 resources: 3 sample pools + 12 equipment items), mirroring the
TypeScript source data exactly.
"""

from __future__ import annotations

DEFAULT_TASKS: list[dict] = [
    # ── env: Environmental tests ──────────────────────────────────
    {
        "num": "1.1",
        "name_en": "Temp Humidity Cycling",
        "name_cn": "温湿度循环测试",
        "section": "env",
        "duration": 4,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0.5,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.2",
        "name_en": "Thermal Shock",
        "name_cn": "热冲击测试",
        "section": "env",
        "duration": 2,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.3",
        "name_en": "High Temp Storage",
        "name_cn": "高温储存测试",
        "section": "env",
        "duration": 3,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0.5,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.4",
        "name_en": "Low Temp Storage",
        "name_cn": "低温储存测试",
        "section": "env",
        "duration": 3,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0.5,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.5",
        "name_en": "Perspiration Test",
        "name_cn": "汗液测试",
        "section": "env",
        "duration": 2,
        "priority": 1,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 4,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.6",
        "name_en": "Electrolytic Corrosion",
        "name_cn": "电解腐蚀测试",
        "section": "env",
        "duration": 3,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 4,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.7",
        "name_en": "Water Resistance",
        "name_cn": "防水测试",
        "section": "env",
        "duration": 2,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.8",
        "name_en": "Salt Spray",
        "name_cn": "盐雾测试",
        "section": "env",
        "duration": 5,
        "priority": 1,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0.5,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.9",
        "name_en": "UV Aging",
        "name_cn": "UV测试",
        "section": "env",
        "duration": 4,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 8,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "1.10",
        "name_en": "Sebum Test",
        "name_cn": "皮脂测试",
        "section": "env",
        "duration": 10,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    # ── mech: Mechanical tests ────────────────────────────────────
    {
        "num": "2.1",
        "name_en": "Tumble Test",
        "name_cn": "耳机滚筒测试",
        "section": "mech",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "2.3",
        "name_en": "Drop Test (Product)",
        "name_cn": "跌落测试(产品)",
        "section": "mech",
        "duration": 1,
        "priority": 1,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "2.4",
        "name_en": "Vibration Test",
        "name_cn": "振动测试",
        "section": "mech",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "2.5",
        "name_en": "Case Lid Life",
        "name_cn": "充电盒开盖寿命",
        "section": "mech",
        "duration": 2,
        "priority": 1,
        "is_serial": True,
        "serial_group": "mech_btn",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": ["2.6"],
        "requirements": [],
    },
    {
        "num": "2.6",
        "name_en": "Button Pressure",
        "name_cn": "按钮压力测试",
        "section": "mech",
        "duration": 1,
        "priority": 0,
        "is_serial": True,
        "serial_group": "mech_btn",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "2.7",
        "name_en": "Button Life",
        "name_cn": "按钮寿命测试",
        "section": "mech",
        "duration": 5,
        "priority": 0,
        "is_serial": True,
        "serial_group": "mech_btn",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": ["2.5"],
        "requirements": [],
    },
    {
        "num": "2.13",
        "name_en": "Ear Tip Pull Force",
        "name_cn": "耳套拔出力测试",
        "section": "mech",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 9,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    # ── surf: Surface / coating tests ─────────────────────────────
    {
        "num": "3.1",
        "name_en": "Rubber Abrasion",
        "name_cn": "橡皮摩擦测试",
        "section": "surf",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "3.7",
        "name_en": "Cross-Cut Test",
        "name_cn": "百格测试",
        "section": "surf",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "product",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    # ── pack: Packaging tests ─────────────────────────────────────
    {
        "num": "4.1",
        "name_en": "High Temp Humidity (Pkg)",
        "name_cn": "高温高湿储存(包装)",
        "section": "pack",
        "duration": 2,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "packaging",
        "sample_qty": 1,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "4.2",
        "name_en": "Low Temp Storage (Pkg)",
        "name_cn": "低温储存(包装)",
        "section": "pack",
        "duration": 3,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "packaging",
        "sample_qty": 1,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "4.3",
        "name_en": "Pressure Test (Pkg)",
        "name_cn": "耐压测试(包装)",
        "section": "pack",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "packaging",
        "sample_qty": 1,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "4.5",
        "name_en": "Drop Test (Pkg)",
        "name_cn": "跌落测试(包装)",
        "section": "pack",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "packaging",
        "sample_qty": 1,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "4.6",
        "name_en": "Drop Test (Gift Box)",
        "name_cn": "跌落测试(礼盒)",
        "section": "pack",
        "duration": 1,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "giftbox",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
    {
        "num": "4.7",
        "name_en": "Hanging Test (Box)",
        "name_cn": "彩盒悬挂测试",
        "section": "pack",
        "duration": 3,
        "priority": 0,
        "is_serial": False,
        "serial_group": "",
        "sample_pool": "giftbox",
        "sample_qty": 3,
        "setup_time": 0,
        "teardown_time": 0,
        "dependencies": [],
        "requirements": [],
    },
]

DEFAULT_RESOURCES: list[dict] = [
    # ── Sample pools ──────────────────────────────────────────────
    {
        "name": "product",
        "type": "sample_pool",
        "category": "sample_pool",
        "unit": "件",
        "available_qty": 12,
        "icon": "🎧",
        "description": "成品样机",
        "unavailable_periods": [],
    },
    {
        "name": "packaging",
        "type": "sample_pool",
        "category": "sample_pool",
        "unit": "件",
        "available_qty": 5,
        "icon": "📦",
        "description": "包装样品",
        "unavailable_periods": [],
    },
    {
        "name": "giftbox",
        "type": "sample_pool",
        "category": "sample_pool",
        "unit": "件",
        "available_qty": 3,
        "icon": "🎁",
        "description": "礼盒样品",
        "unavailable_periods": [],
    },
    # ── Equipment ─────────────────────────────────────────────────
    {
        "name": "恒温恒湿试验箱",
        "type": "equipment",
        "category": "chamber",
        "unit": "台",
        "available_qty": 2,
        "icon": "🌡️",
        "description": "温湿度循环/高温储存/低温储存/高温高湿",
        "unavailable_periods": [],
    },
    {
        "name": "冷热冲击试验箱",
        "type": "equipment",
        "category": "thermal_shock",
        "unit": "台",
        "available_qty": 1,
        "icon": "❄️",
        "description": "热冲击测试",
        "unavailable_periods": [],
    },
    {
        "name": "盐雾试验箱",
        "type": "equipment",
        "category": "salt_spray",
        "unit": "台",
        "available_qty": 1,
        "icon": "🧂",
        "description": "盐雾测试",
        "unavailable_periods": [],
    },
    {
        "name": "UV老化试验箱",
        "type": "equipment",
        "category": "uv_chamber",
        "unit": "台",
        "available_qty": 1,
        "icon": "☀️",
        "description": "UV老化测试",
        "unavailable_periods": [],
    },
    {
        "name": "振动试验台",
        "type": "equipment",
        "category": "vibration",
        "unit": "台",
        "available_qty": 1,
        "icon": "📳",
        "description": "振动测试",
        "unavailable_periods": [],
    },
    {
        "name": "跌落试验机",
        "type": "equipment",
        "category": "drop_test",
        "unit": "台",
        "available_qty": 1,
        "icon": "⬇️",
        "description": "跌落测试",
        "unavailable_periods": [],
    },
    {
        "name": "按钮寿命测试机",
        "type": "equipment",
        "category": "btn_life",
        "unit": "台",
        "available_qty": 2,
        "icon": "🔘",
        "description": "按钮寿命测试/充电盒开盖寿命",
        "unavailable_periods": [],
    },
    {
        "name": "滚筒试验机",
        "type": "equipment",
        "category": "tumble",
        "unit": "台",
        "available_qty": 1,
        "icon": "🌀",
        "description": "耳机滚筒测试",
        "unavailable_periods": [],
    },
    {
        "name": "拉力试验机",
        "type": "equipment",
        "category": "pull_test",
        "unit": "台",
        "available_qty": 1,
        "icon": "💪",
        "description": "耳套拔出力测试/按钮压力测试",
        "unavailable_periods": [],
    },
    {
        "name": "防水测试仪",
        "type": "equipment",
        "category": "water_resist",
        "unit": "台",
        "available_qty": 1,
        "icon": "💧",
        "description": "防水测试",
        "unavailable_periods": [],
    },
    {
        "name": "摩擦仪",
        "type": "equipment",
        "category": "abrasion",
        "unit": "台",
        "available_qty": 1,
        "icon": "🔧",
        "description": "橡皮摩擦测试",
        "unavailable_periods": [],
    },
    {
        "name": "耐压测试仪",
        "type": "equipment",
        "category": "pressure",
        "unit": "台",
        "available_qty": 1,
        "icon": "📐",
        "description": "耐压测试(包装)",
        "unavailable_periods": [],
    },
]
